
prompts_file: "configs/mickey/prompt.yaml"

pretrained_model:
  name_or_path: "CompVis/stable-diffusion-v1-4"
  v2: False
  v_pred: False
  clip_skip: 1

network:
  rank: 1
  alpha: 1.0

train:
  precision: float32
  noise_scheduler: "ddim"
  iterations: 1000
  batch_size: 1
  lr: 0.0002
  unet_lr: 0.0002
  text_encoder_lr: 0.0001
  optimizer_type: "AdamW8bit"
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  lr_scheduler_num_cycles: 0
  max_denoising_steps: 30

save:
  name: "mickey"
  path: "output/mickey"
  per_steps: 1500
  precision: float32

logging:
  use_wandb: false
  interval: 0
  seed: 0
  generate_num: 1
  run_name: "mickey"
  verbose: False
  prompts: ['mickey', '']

other:
  use_xformers: true
